In [102]:
import numpy as np

x = np.random.rand(16).reshape(4,4)
sigz0 = np.array([0.0000001] * 4)
sigz2 = sigz0
sigz2[1] = 0.0001
tau = 1 / (0.05 * 0.05)
S = np.identity(4) * (1/tau) + np.dot(np.dot(x.T, np.diag(sigz2)), x)
np.linalg.inv(S)

array([[ 393.27100775,   -7.42005385,   -5.43073823,   -7.19041717],
       [  -7.42005385,  391.80616437,   -5.99652437,   -7.9296528 ],
       [  -5.43073823,   -5.99652437,  395.60919794,   -5.80459659],
       [  -7.19041717,   -7.9296528 ,   -5.80459659,  392.31451963]])

In [103]:
B0 = np.linalg.inv(np.diag(sigz0)) + tau * np.dot(x, x.T)
B0inv = np.linalg.inv(B0)

zpos = 1
h = 1/0.23 - 1/0.1
hmod = h / (1 + h * B0inv[zpos, zpos])
B1inv = B0inv - hmod * np.einsum('i, j -> ij', B0inv[:,zpos], B0inv[zpos,:])
Sinv = - tau * tau * np.einsum('li, lk, kj -> ij', x, B1inv, x)
Sinv[np.diag_indices_from(C)] += tau
Sinv

array([[ 393.26746863,   -7.4239619 ,   -5.43359976,   -7.19420155],
       [  -7.4239619 ,  391.80184893,   -5.99968419,   -7.93383168],
       [  -5.43359976,   -5.99968419,  395.60688427,   -5.80765643],
       [  -7.19420155,   -7.93383168,   -5.80765643,  392.31047299]])

In [104]:
np.linalg.slogdet(S)[1]

-23.895976528673803

In [106]:
logB0det = np.linalg.slogdet(B0)[1]
logB1det = - 4 * np.log(tau) + 3 * np.log(0.0000001) + np.log(0.0001) +  np.log(1 + h * B0inv[zpos, zpos]) + logB0det
logB1det

-23.896503796843177

In [81]:
np.linalg.det(B1)

27514.047855084824

In [92]:
(1 + h * B0inv[zpos, zpos]) * np.linalg.det(B0)

27514.047855084817

In [83]:
C

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.02984874,  0.58637269,  0.12541157,  0.11996531],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [84]:
np.linalg.det(C)

0.58637268514094787

In [85]:
C[1,1]

0.58637268514094787

In [90]:
1 + h * B0inv[zpos, zpos]

0.58637268514094787