In [33]:
import numpy as np

feat = np.random.rand(40).reshape(10, 4)

In [34]:
feat

array([[ 0.47831784,  0.09630138,  0.89760462,  0.37473957],
       [ 0.04374649,  0.57611062,  0.48120304,  0.21622184],
       [ 0.1030869 ,  0.90786672,  0.23982911,  0.35486645],
       [ 0.30399978,  0.97268247,  0.41514109,  0.50011403],
       [ 0.69377892,  0.56136285,  0.98316322,  0.1382904 ],
       [ 0.90792308,  0.87518703,  0.91146748,  0.00628347],
       [ 0.52119126,  0.82676211,  0.44795639,  0.95553098],
       [ 0.88803107,  0.03726322,  0.99900393,  0.99359272],
       [ 0.56663048,  0.85726734,  0.02417505,  0.29738872],
       [ 0.456502  ,  0.02111801,  0.30954733,  0.22668775]])

In [35]:
featflat = feat.reshape(-1,)
featflat

array([ 0.47831784,  0.09630138,  0.89760462,  0.37473957,  0.04374649,
        0.57611062,  0.48120304,  0.21622184,  0.1030869 ,  0.90786672,
        0.23982911,  0.35486645,  0.30399978,  0.97268247,  0.41514109,
        0.50011403,  0.69377892,  0.56136285,  0.98316322,  0.1382904 ,
        0.90792308,  0.87518703,  0.91146748,  0.00628347,  0.52119126,
        0.82676211,  0.44795639,  0.95553098,  0.88803107,  0.03726322,
        0.99900393,  0.99359272,  0.56663048,  0.85726734,  0.02417505,
        0.29738872,  0.456502  ,  0.02111801,  0.30954733,  0.22668775])

In [42]:
k = 1
i = 9
nsnps = feat.shape[0]
nfeat = feat.shape[1]

feat[ i, k ]

0.0211180103697578

In [43]:
featflat[ i * nfeat + k ]

0.0211180103697578

In [16]:
feat.shape

(10, 4)

In [44]:
params = np.array([-4.0, -2.5, 0, 0.01, 0.001, 0.1])

In [47]:
nhyp = params.shape[0]
scaledparams[ :()]
gammas = params [ :(nhyp - 4) ]
#beta_pi = - np.log((1 / params[0]) - 1)
beta_mu = 100 * params[ nhyp - 4 ]
beta_sigma = np.log(params[ nhyp - 3 ])
beta_sigmabg = np.log(params[ nhyp - 2 ])
beta_tau = - 0.5 * np.log(params[ nhyp - 1])
scaledparams = np.array( list(gammas) + [beta_mu, beta_sigma, beta_sigmabg, beta_tau])

In [49]:
scaledparams

array([-4.        , -2.5       ,  0.        , -4.60517019, -6.90775528,
        1.15129255])

In [53]:
np.append(gammas, np.array(beta_mu))

array([-4. , -2.5,  0. ])

In [55]:
np.ones((10,1)).shape

(10, 1)