In [1]:
import sys
sys.path.append("../")

import numpy as np
import time
import os
import ctypes

In [2]:
_path = os.getcwd()
lib = np.ctypeslib.load_library('../lib/trial.so', _path)
cxtbx = lib.xTBx
cxtbx.restype  = ctypes.c_int
cxtbx.argtypes = [ctypes.c_int,
                  ctypes.c_int,
                  ctypes.c_double,
                  np.ctypeslib.ndpointer(ctypes.c_double, ndim=1, flags='C_CONTIGUOUS, ALIGNED'),
                  np.ctypeslib.ndpointer(ctypes.c_double, ndim=1, flags='C_CONTIGUOUS, ALIGNED'),
                  np.ctypeslib.ndpointer(ctypes.c_double, ndim=1, flags='C_CONTIGUOUS, ALIGNED')]

In [ ]:
x = np.random.rand(24).reshape(4, 6)
B = np.random.rand(16).reshape(4, 4)
np.dot(x.T, np.dot(B, x))

In [ ]:
nrowA  = x.shape[0]
ncolA  = x.shape[1]
nrowB  = B.shape[0]
ncolB  = B.shape[1]
C = np.zeros(ncolA * ncolA)
print(C)
success = cxtbx(nrowA, ncolA, 1.0, x.reshape(-1,), B.reshape(-1,), C)
C.reshape(ncolA, ncolA)

In [3]:
cinv = lib.matloginv
cinv.restype = ctypes.c_double
cinv.argtypes = [ctypes.c_int,
                 np.ctypeslib.ndpointer(ctypes.c_double, ndim=1, flags='C_CONTIGUOUS, ALIGNED')]

In [4]:
matrixSize = 10 
D = np.random.rand(matrixSize,matrixSize)
Dcov = np.dot(D, D.transpose())
Dcov

array([[ 3.51145054,  1.93337301,  3.08437271,  3.21657525,  2.24493976,
         2.03348491,  2.01985014,  2.25057503,  1.88203794,  2.47189908],
       [ 1.93337301,  2.15163776,  1.85753612,  2.31859026,  1.20664346,
         1.22710649,  1.48782284,  1.34494798,  1.35621686,  2.49551264],
       [ 3.08437271,  1.85753612,  4.15976846,  4.09701921,  2.33504546,
         2.18474252,  2.59208648,  2.68471038,  2.00332419,  2.90630012],
       [ 3.21657525,  2.31859026,  4.09701921,  4.96398264,  2.37945627,
         2.30132786,  3.21929126,  3.1064809 ,  2.1451942 ,  3.95500974],
       [ 2.24493976,  1.20664346,  2.33504546,  2.37945627,  2.07588534,
         1.60899574,  1.71604475,  1.94094285,  1.36923793,  1.95740825],
       [ 2.03348491,  1.22710649,  2.18474252,  2.30132786,  1.60899574,
         2.43089651,  1.9573725 ,  2.30639638,  0.77023814,  2.57249635],
       [ 2.01985014,  1.48782284,  2.59208648,  3.21929126,  1.71604475,
         1.9573725 ,  2.43319232,  2.36841216

In [5]:
Dcov.T

array([[ 3.51145054,  1.93337301,  3.08437271,  3.21657525,  2.24493976,
         2.03348491,  2.01985014,  2.25057503,  1.88203794,  2.47189908],
       [ 1.93337301,  2.15163776,  1.85753612,  2.31859026,  1.20664346,
         1.22710649,  1.48782284,  1.34494798,  1.35621686,  2.49551264],
       [ 3.08437271,  1.85753612,  4.15976846,  4.09701921,  2.33504546,
         2.18474252,  2.59208648,  2.68471038,  2.00332419,  2.90630012],
       [ 3.21657525,  2.31859026,  4.09701921,  4.96398264,  2.37945627,
         2.30132786,  3.21929126,  3.1064809 ,  2.1451942 ,  3.95500974],
       [ 2.24493976,  1.20664346,  2.33504546,  2.37945627,  2.07588534,
         1.60899574,  1.71604475,  1.94094285,  1.36923793,  1.95740825],
       [ 2.03348491,  1.22710649,  2.18474252,  2.30132786,  1.60899574,
         2.43089651,  1.9573725 ,  2.30639638,  0.77023814,  2.57249635],
       [ 2.01985014,  1.48782284,  2.59208648,  3.21929126,  1.71604475,
         1.9573725 ,  2.43319232,  2.36841216

In [10]:
res = Dcov.reshape(-1, ).copy()
logdet = cinv(matrixSize, res)
Dcovinv = res.reshape(matrixSize, matrixSize)
logdet

-9.253085618587447

In [20]:
Dcovinv - Dcovinv.T

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [12]:
np.linalg.inv(Dcov)

array([[  18.44335034,  -34.40821508,   18.95615749,  -34.83257169,
         -13.9048531 ,  -27.05360585,  -10.60133455,    8.22936366,
          15.14832714,   47.31017266],
       [ -34.40821508,   77.33000712,  -39.24931297,   69.03514455,
          28.07096118,   53.30932244,   35.53263103,  -19.05256678,
         -37.87870409, -104.65870278],
       [  18.95615749,  -39.24931297,   23.85435364,  -40.76711753,
         -15.54743385,  -30.7667231 ,  -14.03168644,    9.97327737,
          18.15690287,   55.04503495],
       [ -34.83257169,   69.03514455,  -40.76711753,   73.92480183,
          28.00855749,   55.674744  ,   21.59066824,  -18.78701736,
         -32.46230403,  -96.89952488],
       [ -13.9048531 ,   28.07096118,  -15.54743385,   28.00855749,
          13.72966181,   21.07486716,   11.0821529 ,   -9.19288645,
         -14.71551323,  -38.53738568],
       [ -27.05360585,   53.30932244,  -30.7667231 ,   55.674744  ,
          21.07486716,   44.2301037 ,   17.28121372,  -14

In [13]:
np.linalg.slogdet(Dcov)

(1.0, -9.253085618587459)

In [16]:
gy = np.random.rand(matrixSize)

In [17]:
cddot = lib.vTBSYMv
cddot.restype = ctypes.c_double
cddot.argtypes = [ctypes.c_int,
                 np.ctypeslib.ndpointer(ctypes.c_double, ndim=1, flags='C_CONTIGUOUS, ALIGNED'),
                 np.ctypeslib.ndpointer(ctypes.c_double, ndim=1, flags='C_CONTIGUOUS, ALIGNED')]
np.dot(gy.T, np.dot(Dcovinv, gy))

10.744932028226962

In [19]:
cddot(matrixSize, gy, Dcovinv.reshape(-1,))

10.744932028226954